variables:
  configuration: Release
  platform: x64

resources:
- repo: self
  fetchDepth: 5

stages:
- stage: ClangFormat
  jobs:
  - job: ClangFormat
    pool:
      vmImage: Ubuntu-20.04

    variables:
      CC: gcc
      CXX: g++

    steps:
    - bash: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install clang-format-9 ninja-build python3
      displayName: 'Install'
    - task: PythonScript@0
      displayName: 'Build'
      inputs:
        scriptPath: BuildAll.py
        arguments: 'ninja gcc linux clangformat'
    - script: |
        git diff --exit-code $(Build.SourceVersion)
      failOnStderr: true
      displayName: 'Clang-Format'

- stage: Build
  condition: succeeded('ClangFormat')
  jobs:

  - job: Windows_vc141_x64
    pool:
      vmImage: VS2017-Win2016

    variables:
      compiler: vc141
      combination: 'win-$(compiler)-$(platform)-$(configuration)'
      buildFolder: 'Build/ninja-$(combination)'
      installCommand: 'choco install ninja python3'
      testCommand: './$(buildFolder)/Bin/ShaderConductorTest.exe'
      artifactBinaries: |
        Bin/ShaderConductor.dll
        Bin/ShaderConductorCmd.exe
        Bin/dxcompiler.dll
        Lib/ShaderConductor.lib

    steps:
    - template: CI/AzurePipelines/ContinuousBuild.yml

  - job: Linux_gcc8
    pool:
      vmImage: Ubuntu-20.04

    variables:
      compiler: gcc8
      combination: 'linux-$(compiler)-$(platform)-$(configuration)'
      buildFolder: 'Build/ninja-$(combination)'
      installCommand: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install g++-8 ninja-build python3
      testCommand: './$(buildFolder)/Bin/ShaderConductorTest'
      artifactBinaries: |
        Bin/ShaderConductorCmd
        Lib/libdxcompiler.so
        Lib/libShaderConductor.so
      CC: gcc-8
      CXX: g++-8

    steps:
    - template: CI/AzurePipelines/ContinuousBuild.yml

  - job: macOS_10_clang
    pool:
      vmImage: macOS-11

    variables:
      compiler: clang9
      combination: 'osx-$(compiler)-$(platform)-$(configuration)'
      buildFolder: 'Build/ninja-$(combination)'
      installCommand: |
        brew update
        brew install ninja
      testCommand: './$(buildFolder)/Bin/ShaderConductorTest'
      artifactBinaries: |
        Bin/ShaderConductorCmd
        Lib/libdxcompiler.dylib
        Lib/libShaderConductor.dylib
      CC: clang
      CXX: clang++

    steps:
    - template: CI/AzurePipelines/ContinuousBuild.yml
